### ISSUE TITLE
Documentation path to NERSC data (soon-to-be) out of date

### ISSUE THREAD

**Issue by jaejoonk** [galsci/mapsims#88]
The path for the CMB lensed simulations listed here: https://mapsims.readthedocs.io/en/latest/camb.html

`/global/project/projectdirs/sobs/v4_sims/mbs/cmb/`

will be out-of-date once we reach the retirement date for NERSC's Cori clusters on May 31, 2023 (less than a month from the time of writing); the appropriate Perlmutter path with all of the data is:

`/global/cfs/cdirs/sobs/v4_sims/mbs/cmb/`

Thanks!

**Comment by zonca** [comment]
thanks! didn't realize that.
Would you mind doing a pull request to fix this?
otherwise I'll get to it in a couple of weeks
